export const adminAction = {
  //fail action types to be added

  ADD_USER_INITIATTE: 'ADD_USER_INITIATE',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  DELETE_USER_INITIATE: 'DELETE_USER_INITIATE',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  EDIT_USER_INITIATE: 'EDIT_USER_INITIATE',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  FETCH_USER_INITIATE:'FETCH_USER_INITIATE',
  FETCH_USER_SUCCESS:'FETCH_USER_SUCCESS'
}